"""
A spinning 360-degree Lidar, driven from a motor HAT position and streaming
measurements over a UART.

WHY IT IS A MOTOR LOAD
----------------------
The head spins because an H-bridge is driving it, exactly like a wheel. So the Lidar is
a load on a :class:`~armulator.peripherals.motor_hat.MotorChannel`, not a peripheral of
its own:

    hat = MotorHat().attach_to(board)
    lidar = Lidar(room=Room(4.0))
    lidar.attach_to(hat, 4)
    lidar.connect(board.uart)

That gets two things for free. Firmware spins the head by writing PCA9685 registers, so
the "is the motor actually running" failure mode is reachable from driver code rather
than stipulated. And :meth:`MotorHat.advance` already fans out to everything in its
``motors`` dict, so registering there means the Lidar shares the HAT's clock instead of
inventing a second one that can drift away from it.

THE ANGLE PROBLEM
-----------------
A range is meaningless without the bearing it was taken at, so the head's angular
position is load-bearing here in a way MOTOR.md explicitly says it is not for a wheel
("there is no encoder to read"). The position comes from the spindle's integrated
:attr:`~armulator.peripherals.motor.DcMotor.position`, which the model computes exactly.
That is a real departure from hardware: a physical unit derives angle from an index pulse
and sample timing, and a driver that mishandles that has nowhere to go wrong here. What
this does model is the consequence firmware actually cares about -- spin the head slower
and the same sample rate spreads fewer points over each revolution.

Samples are generated by interpolating the head's angle across the advance interval and
ray-casting at each one. Below :attr:`SPIN_THRESHOLD` nothing is emitted at all, because
a stationary head does not produce a scan; it produces the same bearing forever, and
reporting that as thousands of valid measurements would be a lie a driver could not
detect.
"""

import math
from collections import namedtuple

from armulator.peripherals.motor import DcMotor
from armulator.sensors.geometry import Room

#: One measurement. ``distance`` is metres, or None for no return. ``start`` marks the
#: first sample of a revolution, which is how a driver knows where a scan begins.
Measurement = namedtuple('Measurement', ['angle', 'distance', 'start', 'quality'])

# ---------------------------------------------------------------------------
# RPLIDAR serial protocol
# ---------------------------------------------------------------------------

#: Every command from the host starts with this.
SYNC = 0xA5
#: Every response descriptor starts with SYNC then this.
SYNC_RESPONSE = 0x5A

CMD_STOP = 0x25
CMD_RESET = 0x40
CMD_SCAN = 0x20
CMD_GET_INFO = 0x50
CMD_GET_HEALTH = 0x52

#: Descriptors: (payload length, mode, data type). Mode 1 means a continuous stream.
DESCRIPTORS = {
    CMD_SCAN: (5, 1, 0x81),
    CMD_GET_INFO: (20, 0, 0x04),
    CMD_GET_HEALTH: (3, 0, 0x06),
}

#: Health status byte: good.
HEALTH_GOOD = 0


def encode_descriptor(length, mode, data_type):
    """
    Build the seven-byte response descriptor that precedes every reply.

    Length is 30 bits and mode is 2, packed into the same four bytes, which is the
    detail drivers most often get wrong when parsing this protocol by hand.
    """
    packed = (length & 0x3FFFFFFF) | ((mode & 0x3) << 30)
    return bytes([
        SYNC, SYNC_RESPONSE,
        packed & 0xFF, (packed >> 8) & 0xFF, (packed >> 16) & 0xFF,
        (packed >> 24) & 0xFF,
        data_type & 0xFF,
    ])


def encode_measurement(measurement):
    """
    Pack a :class:`Measurement` into the five-byte node the A-series streams.

    ====  ==========================================================
    Byte  Contents
    ====  ==========================================================
    0     quality in the top 6 bits, then !start, then start
    1     low 7 bits of angle in q6 degrees, then a always-set check bit
    2     high bits of angle
    3-4   distance in q2 millimetres, little endian; 0 means no return
    ====  ==========================================================

    The redundant inverted start bit and the check bit in byte 1 exist so a receiver
    that has lost framing can resynchronise. They are reproduced faithfully because a
    driver's resync logic is worth being able to test.
    """
    angle_q6 = int(round(measurement.angle * 64.0)) & 0xFFFF
    if measurement.distance is None:
        distance_q2 = 0
    else:
        distance_q2 = int(round(measurement.distance * 1000.0 * 4.0)) & 0xFFFF
    start = 1 if measurement.start else 0
    quality = measurement.quality & 0x3F
    return bytes([
        (quality << 2) | ((start ^ 1) << 1) | start,
        ((angle_q6 & 0x7F) << 1) | 1,
        (angle_q6 >> 7) & 0xFF,
        distance_q2 & 0xFF,
        (distance_q2 >> 8) & 0xFF,
    ])


def decode_measurement(node):
    """
    Unpack a five-byte node. The inverse of :func:`encode_measurement`.

    :raises ValueError: if the framing bits are wrong, which is what a receiver that
        has lost sync sees
    """
    if len(node) != 5:
        raise ValueError(f'a measurement node is 5 bytes, not {len(node)}')
    start = node[0] & 0x1
    inverted = (node[0] >> 1) & 0x1
    if start == inverted:
        raise ValueError('start bit and its inverse agree; framing is lost')
    if not node[1] & 0x1:
        raise ValueError('check bit clear; framing is lost')
    angle = (((node[1] >> 1) | (node[2] << 7)) & 0xFFFF) / 64.0
    distance_q2 = node[3] | (node[4] << 8)
    distance = None if distance_q2 == 0 else distance_q2 / 4000.0
    return Measurement(angle, distance, bool(start), node[0] >> 2)


class Lidar:
    """
    :param room: the world to range against
    :param sample_rate: measurements per second, independent of spin speed
    :param max_range: beyond this, a surface returns nothing
    :param min_range: closer than this, a surface returns nothing
    :param free_speed: head speed at full drive, in revolutions per second
    :param pose: ``(x, y, heading)`` -- where the unit sits and which way its zero
        bearing points, in metres and radians

    Sample rate and spin speed are deliberately independent, because on real hardware
    they are: the ranging engine fires at a fixed rate and the motor turns at whatever
    the PWM says. Points per revolution falls out of the ratio, and a driver that spins
    too fast gets a sparse scan rather than an error.
    """

    #: Revolutions per second below which the head is not considered to be scanning.
    SPIN_THRESHOLD = 0.2

    #: Signals the telemetry recorder picks up, on top of the bridge ones.
    TELEMETRY_FIELDS = ('angle', 'rpm', 'revolutions', 'scanning', 'last_range')

    def __init__(self, room=None, sample_rate=4000, max_range=6.0, min_range=0.15,
                 free_speed=5.5, pose=(0.0, 0.0, 0.0), name='lidar'):
        if sample_rate <= 0:
            raise ValueError(f'sample rate must be positive, not {sample_rate}')
        self.name = name
        self.room = room if room is not None else Room()
        self.sample_rate = sample_rate
        self.max_range = max_range
        self.min_range = min_range
        self.pose = tuple(pose)

        #: The motor turning the head. Its bridge is what the HAT drives.
        self.spindle = DcMotor(free_speed=free_speed, name=f'{name}_spindle')

        #: Every measurement generated, whether or not a UART was listening.
        self.measurements = []
        #: The most recent complete revolution, as a list of measurements.
        self.last_scan = []
        #: Completed revolutions since power-on.
        self.revolutions = 0

        self.uart = None
        self.streaming = False
        #: Commands the host has sent, as (command, payload) - for assertions.
        self.commands = []

        self._scan_buffer = []
        self._sample_credit = 0.0
        self._last_turn = None
        self._rx = bytearray()
        self._last_range = None

    # ------------------------------------------------------------------
    # Wiring
    # ------------------------------------------------------------------

    def attach_to(self, hat, index):
        """
        Plug the head's motor into motor position ``index`` on ``hat``.

        Registering in the HAT's ``motors`` dict is what makes ``hat.advance()`` drive
        this; the Lidar stands in for a plain motor there because it has the same
        ``advance(seconds)`` interface.
        """
        if index not in hat.channels:
            raise ValueError(f'motor position must be one of {sorted(hat.channels)}')
        channel = hat.channels[index]
        channel.bridge = self.spindle.bridge
        channel.load = self
        hat.motors[index] = self
        self.hat = hat
        return self

    def connect(self, uart):
        """
        Attach to a UART: parse host commands from its transmit side, stream
        measurements into its receive side.

        Duck-typed against ``tx_callbacks`` and ``feed``, so either the PL011 or the
        8250 works, as does anything else offering the same two things.
        """
        self.uart = uart
        uart.tx_callbacks.append(self._host_byte)
        return self

    # ------------------------------------------------------------------
    # Spinning and ranging
    # ------------------------------------------------------------------

    @property
    def angle(self):
        """Current head bearing in degrees, 0-360."""
        return (self.spindle.position * 360.0) % 360.0

    @property
    def rpm(self):
        return self.spindle.speed * 60.0

    @property
    def scanning(self):
        """Whether the head is turning fast enough to produce a scan."""
        return abs(self.spindle.speed) >= self.SPIN_THRESHOLD

    @property
    def last_range(self):
        """Most recent range in metres; 0.0 for no return, so it is always plottable."""
        return 0.0 if self._last_range is None else self._last_range

    @property
    def points_per_revolution(self):
        """
        How many samples a full turn gets at the current speed, or None when stopped.
        """
        if not self.scanning:
            return None
        return self.sample_rate / abs(self.spindle.speed)

    def range_at(self, bearing_degrees):
        """
        Range along a bearing measured in the *room*, not relative to the head.

        Returns None for no return, which is either out of range or too close.
        """
        x, y, _ = self.pose
        distance = self.room.range_at((x, y), math.radians(bearing_degrees))
        if distance is None:
            return None
        if distance > self.max_range or distance < self.min_range:
            return None
        return distance

    def advance(self, seconds):
        """
        Spin the head for ``seconds`` and generate whatever samples fit.

        Called by :meth:`MotorHat.advance`; a caller does not normally invoke it.
        """
        if seconds <= 0:
            return

        start_turn = self.spindle.position
        self.spindle.advance(seconds)
        end_turn = self.spindle.position

        self._sample_credit += seconds * self.sample_rate
        count = int(self._sample_credit)
        self._sample_credit -= count
        if count <= 0 or not self.scanning:
            # Credit is kept rather than discarded, so a run of intervals shorter than
            # one sample period still eventually produces a sample instead of silently
            # dropping every one of them.
            return

        for step in range(1, count + 1):
            turn = start_turn + (end_turn - start_turn) * (step / count)
            self._emit(turn)

    def _emit(self, turn):
        """Take one measurement with the head at ``turn`` revolutions."""
        _, _, heading = self.pose
        angle = (turn * 360.0) % 360.0
        bearing = angle + math.degrees(heading)
        distance = self.range_at(bearing)
        self._last_range = distance

        start = False
        revolution = math.floor(turn)
        if self._last_turn is not None and revolution != self._last_turn:
            # The head has crossed zero: close the scan and flag the next sample.
            start = True
            self.revolutions += 1
            if self._scan_buffer:
                self.last_scan = self._scan_buffer
            self._scan_buffer = []
        self._last_turn = revolution

        measurement = Measurement(angle, distance, start, quality=47)
        self.measurements.append(measurement)
        self._scan_buffer.append(measurement)

        if self.streaming and self.uart is not None:
            self.uart.feed(encode_measurement(measurement))

    # ------------------------------------------------------------------
    # Host protocol
    # ------------------------------------------------------------------

    def _host_byte(self, byte):
        """
        One byte arrived from firmware. Commands are SYNC then an opcode.

        Anything before a SYNC is discarded rather than buffered, which is what the
        hardware does and means a driver that starts mid-stream still syncs up.
        """
        if not self._rx:
            if byte != SYNC:
                return
            self._rx.append(byte)
            return
        self._rx.append(byte)
        command = self._rx[1]
        self._rx.clear()
        self._handle(command)

    def _handle(self, command):
        self.commands.append(command)
        if command == CMD_SCAN:
            self._respond(CMD_SCAN)
            self.streaming = True
        elif command in (CMD_STOP, CMD_RESET):
            self.streaming = False
            if command == CMD_RESET:
                self.measurements = []
                self.last_scan = []
                self.revolutions = 0
                self._scan_buffer = []
                self._last_turn = None
        elif command == CMD_GET_INFO:
            self._respond(CMD_GET_INFO)
            self._send(self._info_payload())
        elif command == CMD_GET_HEALTH:
            self._respond(CMD_GET_HEALTH)
            self._send(bytes([HEALTH_GOOD, 0, 0]))
        # Unknown commands are ignored, as they are by the hardware.

    def _respond(self, command):
        self._send(encode_descriptor(*DESCRIPTORS[command]))

    def _send(self, data):
        if self.uart is not None:
            self.uart.feed(data)

    def _info_payload(self):
        """Model, firmware minor/major, hardware, then a 16-byte serial number."""
        return bytes([0x18, 0x00, 0x01, 0x05]) + bytes(range(16))

    # ------------------------------------------------------------------
    # Inspection
    # ------------------------------------------------------------------

    def scan_points(self, scan=None):
        """
        The last complete revolution as ``(angles, ranges)`` in degrees and metres.

        No-return samples are dropped rather than plotted as zero, because a zero range
        would draw a spurious line to the origin.
        """
        scan = self.last_scan if scan is None else scan
        angles = [m.angle for m in scan if m.distance is not None]
        ranges = [m.distance for m in scan if m.distance is not None]
        return angles, ranges

    def __repr__(self):
        state = 'scanning' if self.scanning else 'stopped'
        return (f'<Lidar {self.name} {state} {self.rpm:.0f}rpm '
                f'{self.revolutions} revs {len(self.measurements)} samples>')
